# Generated by Django 3.2 on 2022-02-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keto', '0004_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='meals',
        ),
        migrations.AddField(
            model_name='food',
            name='days',
            field=models.ManyToManyField(blank=True, related_name='food_list', to='keto.Day'),
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
