# Generated by Django 3.2 on 2022-02-07 19:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='keto_weeks',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Breakfast', max_length=25)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='keto.day')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField(default=0.0)),
                ('carbs', models.FloatField(default=0.0)),
                ('calories', models.FloatField(default=0.0)),
                ('fat', models.FloatField(default=0.0)),
                ('protein', models.FloatField(default=0.0)),
                ('sugar', models.FloatField(default=0.0)),
                ('fiber', models.FloatField(default=0.0)),
                ('saturated', models.FloatField(default=0.0)),
                ('trans', models.FloatField(default=0.0)),
                ('chol', models.FloatField(default=0.0)),
                ('sodium', models.FloatField(default=0.0)),
                ('added_sugar', models.FloatField(default=0.0)),
                ('chol_dv', models.FloatField(default=0.0)),
                ('sodium_dv', models.FloatField(default=0.0)),
                ('meal', models.ManyToManyField(blank=True, related_name='food_list', to='keto.Meal')),
            ],
        ),
    ]
