# Generated by Django 3.2 on 2022-02-10 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keto', '0005_auto_20220208_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activ',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='days', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servings', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=100, null=True)),
                ('instructions', models.TextField(null=True)),
                ('ingredients', models.TextField(null=True)),
                ('weight', models.FloatField(default=0.0)),
                ('carbs', models.FloatField(default=0.0)),
                ('calories', models.FloatField(default=0.0)),
                ('fat', models.FloatField(default=0.0)),
                ('protein', models.FloatField(default=0.0)),
                ('sugar', models.FloatField(default=0.0)),
                ('fiber', models.FloatField(default=0.0)),
                ('saturated', models.FloatField(default=0.0)),
                ('trans', models.FloatField(default=0.0)),
                ('chol', models.FloatField(default=0.0)),
                ('sodium', models.FloatField(default=0.0)),
                ('added_sugar', models.FloatField(default=0.0)),
                ('chol_dv', models.FloatField(default=0.0)),
                ('sodium_dv', models.FloatField(default=0.0)),
                ('days', models.ManyToManyField(blank=True, related_name='recipes_eaten', to='keto.Day')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(null=True)),
                ('rating', models.IntegerField(null=True)),
                ('recipe', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_list', to='keto.recipe')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
