# Generated by Django 3.2 on 2022-02-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keto', '0009_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
