# Generated by Django 3.2 on 2022-02-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keto', '0010_alter_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daily_carb',
            field=models.IntegerField(default=50),
        ),
    ]
