# Generated by Django 3.2 on 2022-02-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keto', '0012_auto_20220210_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='daily_carb',
            field=models.FloatField(default=30.0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='daily_fat',
            field=models.FloatField(default=150.0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='daily_sugar',
            field=models.FloatField(default=10.0),
        ),
    ]
