# Generated by Django 3.2 on 2022-02-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keto', '0013_auto_20220210_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='newsType',
            field=models.CharField(default='post', max_length=25),
        ),
    ]
