# Generated by Django 3.2 on 2022-02-12 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keto', '0014_post_newstype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='newsType',
        ),
    ]
