# Generated by Django 3.2 on 2022-02-13 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keto', '0015_remove_post_newstype'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
