# Generated by Django 3.2 on 2022-02-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keto', '0016_profile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='decimals',
            field=models.IntegerField(default=0),
        ),
    ]
